apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: enforce-annotations
  labels:
    app: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      annotations:
        # invalid annotation
        "k8s.questionable.services/id": "abc"
        "mifomm.eu/name": "RH"
        # valid annotation
        #"k8s.questionable.services/hostname": "abc.example.com"
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: mifomm/goservd-amd64:0.0.7
          resources:
            requests:
              cpu: 25m
              memory: 263M
            limits:
              cpu: 25m
              memory: 263M                
          ports:
            - containerPort: 5000